# Generated by Django 2.2 on 2019-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=230)),
                ('address', models.CharField(max_length=130)),
                ('userPhone', models.CharField(max_length=130)),
                ('otherMsg', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('time', models.CharField(max_length=230)),
                ('amount', models.CharField(max_length=130)),
                ('kind', models.CharField(max_length=230)),
                ('otherMsg', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='OfferMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=230)),
                ('number', models.CharField(max_length=30)),
                ('count', models.CharField(max_length=130)),
                ('prize', models.CharField(max_length=30)),
                ('othermsg', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=130)),
            ],
        ),
    ]
