# Generated by Django 2.2 on 2019-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendWaterBG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('passed', models.CharField(max_length=130)),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='offerman',
            name='count',
        ),
        migrations.RemoveField(
            model_name='offerman',
            name='prize',
        ),
        migrations.AddField(
            model_name='committable',
            name='kind',
            field=models.CharField(default='none', max_length=130),
        ),
        migrations.AddField(
            model_name='committable',
            name='name',
            field=models.CharField(default='d', max_length=30),
            preserve_default=False,
        ),
    ]
