# Generated by Django 2.2 on 2019-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendWaterBG', '0003_admin_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='committable',
            name='shopname',
            field=models.CharField(default='none', max_length=130),
        ),
        migrations.AddField(
            model_name='committable',
            name='shopnumber',
            field=models.CharField(default='none', max_length=130),
        ),
    ]
